### ISSUE TITLE
Remove container on exit?

### ISSUE THREAD

**Issue by MatthiasSchilder** [mariotoffia/FluentDocker#100]
Hi,

I have a container which contains a particular, long running executable, which finishes after a few hours. It then should copy it's results as a file to the host and exit. This container-exit should trigger the removal of said container.

As far as I understood, FluentDocker automatically removes containers on disposal, so my idea was to wrap everything in an using-block and stall the thread execution (and so the immediate disposal) with a WaitHandle, which is released when the container state changes:

```csharp
 private ManualResetEvent handle = new ManualResetEvent(false);

using (var container = new Builder()
		.DefineImage(imageName)
		.ReuseIfAlreadyExists()
		.From("my/image")
		.Command("cmd")
		.Builder()
		.UseContainer()
		.WithName("qwertz")
		.UseImage(imageName)
		.IsWindowsImage()
        [...]
		.Builder()
		.Build())
{
	container.StateChange += ContainerOnStateChange;
	var svc = container.Start();

	handle.WaitOne();
}

private void ContainerOnStateChange(object sender, StateChangeEventArgs evt)
{
	if(evt.State == ServiceRunningState.Stopped)
		handle.Set();
}
```

Unfortunately, this does not work. It looks like the StateChange event never fires. Is there a better way to achieve the wanted behaviour? My last fill-in would be to use .Wait and look for the expected files in the hosts filesystem, but this looks not really robust to me.

Thank you.

**Comment by mariotoffia** [comment]
Hi, the container will change state and dispose when the container variable is Disposed. You need to do your handler set and then it will change state while disposing. The example above will never change state since container variable is not disposed. I hope this clarifies your problem?

**Comment by MatthiasSchilder** [comment]
Hi, yes, I understood that. The problem is I don't know how I can wait for the container command to finish and then dispose it. Container.Start() immediately returns after the container is up; when written in an empty using block, directly after it is disposed, before the container finishes it's specified command. So I need a wait to wait in the body of the using block. My idea was to react on the state change of the container, which is triggered when the container command has finished. Is this not possible?

**Comment by mariotoffia** [comment]
It is by design that the library won't do anything except when you tell it to. So that means that I probably never implement a listener to drive the states in the services. Those are just when you drive the states.

Having said that, there are, for now three possibilities:
1) Use the `Log().ReadToEnd()` that releases the control when cancellation token is signalled or the container has exited.
```cs
using (
          var container =
            Fd.UseContainer()
              .WithName("internal-container")
              .UseImage("alpine")
              .Command("ping", "1.1.1.1", "-c 1", "-w 5", "-W 5")
              .Build()
              .Start())
        {
           var log = container.Logs().ReadToEnd(30_000);
           // When ping has finished
        }
```
This may be reliant, but haven't experienced much testing. It has been used in a simple unittest so far...

2) Use The `Logs(follow: true)` extension with `follow` set to `true`.
```cs
using (
          var container =
            Fd.UseContainer()
              .WithName("internal-container")
              .UseImage("alpine")
              .Command("ping", "1.1.1.1", "-c 1", "-w 5", "-W 5")
              .Build()
              .Start())
        {
           var log = container.Logs(follow: true);
           // When ping has finished
        }
```
This may be really stable, but has never been tested (`follow: true`) but in theory shall work flawless. It is possible to use `CancellationToken` as well here to cancel the operation.

3) Use `docker events` to read events - it has never been tested and I suspect that those are _JSON_ and needs deserializing and create real events.
```cs
using (
          var container =
            Fd.UseContainer()
              .WithName("internal-container")
              .UseImage("alpine")
              .Command("ping", "1.1.1.1", "-c 1", "-w 5", "-W 5")
              .Build()
              .Start())
        {
           var events = container.Host.Events();
        }
```
This needs to be investigated further.

I hope the above gives a few pointer, please tell me how you solved it and if it is stable or needs to file a bug (or two ;)

Cheers,
 Mario
