### ISSUE TITLE
Create release for "WaitForMessageInLog"

### ISSUE THREAD

**Issue by seertenedos** [mariotoffia/FluentDocker#124]
I have a use case that needs the exact functionality you jsut added. Is there any chance you could put your latest changes in a release or a pre-release?

**Comment by mariotoffia** [comment]
Yes, I've created a pre-release support in the build based in the Issue #123. Same author of that Issue is the author of `WaitForMessageInLog`. Try to include (tick include pre-release) or use this link and have a go https://www.nuget.org/packages/Ductus.FluentDocker/2.7.4-beta0001.

Cheers,
 Mario :)

**Comment by seertenedos** [comment]
Thanks that is perfect
