### ISSUE TITLE
Lambda not called in WaitForHttp

### ISSUE THREAD

**Issue by cotepatrice** [mariotoffia/FluentDocker#153]
I try to wait for a response to contain something like in your sample (in README.md), but it doesn't seem to work.

I use a docker-compose file and added the WaitForHttp extension like this : 

```
using (var svc = new Ductus.FluentDocker.Builders.Builder()
                              .UseContainer()
                              .UseCompose()
                              .FromFile(file)
                              .RemoveOrphans()
                              .WaitForHttp("myservice", "http://localhost:2020/myPage/", continuation: (resp, cnt) =>
                                            {
                                                Debug.WriteLine("Inside continuation");
                                                return resp.Body.IndexOf("Client Number", StringComparison.Ordinal) != -1 ? 0 : 500;
                                            }, contentType: "text/html")
                              .Build().Start())
```
I added a breakpoint inside the lambda to but it doesn't stop inside. I'm running this inside a .Net Core 3.1 Console project. Can you see what I do wrong or is it just broken? 

Note that the docker compose file works and the call ends up launching everything right, but I must wait for DB to be ready to run a script.

Installed version from Nuget : 2.7.3

**Comment by mariotoffia** [comment]
Is your project called _myservice_? For example in a unit test I use a docker compose where the service to wait for is the `wordpress` below. When the service (docker compose project in this case) "myservice" switches to state running, it will do the `WaitForHttp`. If no such service or the service will never reach running the `WaitForHttp` is never invoked.

```cs
 builder.WaitForHttp("wordpress", "http://localhost:8000/wp-admin/install.php",
     continuation: (resp, cnt) =>  { /* continuation code here */ })
```

The project name is either from the name (e.g. if compose file is in a folder called wordpress) if it matches the <project name>_<instance id> format or from the label `com.docker.compose.project`. Since the docker-compose.yaml` will render a `ICompositeService` with the name of the project the above must match the project name in order to be executed.

**Comment by cotepatrice** [comment]
Yes, myService and myPage are just placeholders for this example purpose. I didn't get the use of the "project" concept here, I used the service name. Since it is a docker-compose file, it launches x number of services and we should be able to wait for a single one with the service name., not all the project service stack. Like the concept of "depends-on" in docker-compose. Anyway, this is more of a suggestion here since I made a workaround of my own for my use case. Thanks for the answer.

**Comment by pavanupb** [comment]
@mariotoffia I have similar issue. I tried adding my docker compose project name to WaitForHttp but still no luck.

**Comment by bbotiroff** [comment]
Came across this and did not see the proper answer. Just figured out, for it to go to that point, either you'll need to define the `container_name` in your dockerfile something static string and use that string as a service (first argument) of this method. Or run your docker-compose locally from the terminal and grab the container name from there.
