### ISSUE TITLE
How to use dynamic parameter

### ISSUE THREAD

**Issue by MinhDuc010194** [mariotoffia/FluentDocker#169]
docker run
 --mount type=bind,source=F:/Working/test,target=/opt/ts3d/cadfiles
 --mount type=bind,source=F:/Working/test,target=/opt/ts3d/output 
 techsoft3d/communicator-converter
 --input /opt/ts3d/cadfiles/a.rvt
 --output_sc /opt/ts3d/output/output_sc_model
 --sc_create_scz 1 --sc_compress_scz 0
 --output_png /opt/ts3d/output/output.png
 --license "key"

Is it possible to run the docker command above using FluentDocker?
I really want FluentDocker support to inject more dynamic parameters like   --license "key". this is the parameter I'm used for the .sh file.
`
#!/usr/bin/bash
/usr/bin/xvfb-run
 "--auto-servernum" "-s" "-screen 0 640x480x24" /opt/ts3d/bin/linux64/converter "$@"
`

**Comment by mariotoffia** [comment]
@MinhDuc010194  Hi and thanks for reaching out - been on holiday and that's why the late response...

Unfouranly no, but it may be easily added, instead of:
[Client.cs](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Commands/Client.cs#L170)

```cs
public static CommandResponse<string> Run(this DockerUri host, string image, ContainerCreateParams args = null,
      ICertificatePaths certificates = null)
{
  // Do execute Run
}
```

One may add e.g. 

```cs
public static CommandResponse<string> Run(this DockerUri host, string image, ContainerCreateParams args = null,
      ICertificatePaths certificates = null, params string[] extra)
{
  var extras = string.Join(", ", extra);
  // Do exeecute Run with the extras at the end
}
```

Around how [Create](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Commands/Client.cs#L141) function does it (just above the run function)

Is this what you wanted?

Cheers,
 Mario :)

**Comment by mariotoffia** [comment]
Closing the issue since inactivity.
