### ISSUE TITLE
Using FluentDocker from .net code running in a container to stop another container on the same docker host

### ISSUE THREAD

**Issue by chris-zengenti** [mariotoffia/FluentDocker#199]
Hey guys,

Thanks for providing this amazing package - it's great.

Do you have any examples, use-cases or awareness of using FluentDocker from a .net core application running in a container to stop a container running in the same docker host that the application container is running in?  For example,

Running a unit test  in a container that stops a container running MessageQueue software and testing the unit of work to make assertions on its behaviour in that scenario.

Would I have to provide the remote URL?  The error I'm getting is  `Ductus.FluentDocker.Common.FluentDockerException : Failed to find docker client binary - please add it to your path`, which makes sense as Docker is not running inside my container - but what URI should I provide in order to connect to it?

Cheers
Chris

**Comment by mariotoffia** [comment]
Hi @chris-zengenti - nice that you like the library! :)

It has already been answered, but for windows, just replace the docker socket mount to Linux one if you run Unix containers (use [/var/run/docker.sock](https://betterprogramming.pub/about-var-run-docker-sock-3bfd276e12fd) instead).

Please see Issue #93 - hope it helps?

Cheers,
 Mario :)

**Comment by chris-zengenti** [comment]
Thanks for getting back so quickly Mario!

I'll give it a go later today and let you know  😉

**Comment by cpneale** [comment]
Hi Mario,

only just got around to looking at this. I’ve read issue 93 and a couple of other resources here[here](https://stackoverflow.com/questions/35110146/can-anyone-explain-docker-sock) and [here](https://docs.docker.com/engine/reference/commandline/dockerd/#examples). 

So, am I correct in thinking I need to have the docket client running on my container (installed on the image via dockerfile) and then map the docker socket mount on the container to the docker deamon socket on the host machine (Linux)? I should be ok with the first part but not quite sure what to use in the -v option to mount the dockerd socket.

**Comment by mariotoffia** [comment]
Hi @cpneale , by default the linux docker client will try to contact the docker daemon on _unix:///var/run/docker.sock_ and hence if you start your docker container with _-v /var/run/docker.sock:/var/run/docker.sock_ it will do *exactly* what your'e after :)

💡 NOTE: Since by default, _FluentDocker_ will pick up the default daemon address and will work as it would executed on the host itself and hence not aware that it is in a container when the socket has been mounted in the above way!

Easiest way is to get a contains that e.g. supports bash and do `docker run --rm -it --entrypoint bash -v /var/run/docker.sock:/var/run/docker.sock <<dockerhub image here>>`

in my case it will emit the following on `docker ps -a`:
```bash
docker run --rm -it --entrypoint bash -v /var/run/docker.sock:/var/run/docker.sock docker-in-docker
root@a28c90a0b112:/App# docker ps -a
CONTAINER ID   IMAGE              COMMAND   CREATED         STATUS         PORTS     NAMES
a28c90a0b112   docker-in-docker   "bash"    3 seconds ago   Up 2 seconds             adoring_booth
```

Hope it helps!
  Mario :)

**Comment by cpneale** [comment]
Works perfectly! Thanks for your help and the docker lesson! 🙏🙌❤️
