### ISSUE TITLE
Create image from Dockerfile (more "pretty" API)

### ISSUE THREAD

**Issue by lorenzo93** [mariotoffia/FluentDocker#54]
Hi,

I've started using your library yesterday. It is very useful and looks like there is an option for everything.

The only thing I cannot find is how to create an image from a Dockerfile.
Is this function available?

Thank you

**Comment by mariotoffia** [comment]
Hi, I'm glad that you like it! - If you really like please star it ;). You can specify either a docker file or a docker file as a string using the builder. Please see the _FluentMultiContainerTests.cs_. Instead of defining a dockerfile you can replace with eg. 

```
          new Builder()
          .DefineImage("mariotoffia/nodetest").ReuseIfAlreadyExists()
          .From("")
          .FromFile("my-docker-file")
          .Build();
```

This will create a image from the specified dockerfile. The first from can be ignored (I will update the api so it accept fromfile directly at a later point).

Cheers,
 Mario

**Comment by mariotoffia** [comment]
I'm closing this issue. Next release will have the more "pretty" builder api.

Cheers,
 Mario
