### ISSUE TITLE
Support for Interactive Mode

### ISSUE THREAD

**Issue by lorenzo93** [mariotoffia/FluentDocker#65]
Hi,

Is there an option to launch an external (interactive) shell (powershell on windows and bash on linux) attached to a docker container?

It would be wonderfult to have a command on `DockerContainerService` that opens an external window with some specific command, like you can do with 
`docker run -ti alpine /bin/sh`

Maybe something that returns to you a `Task` so I can continue the execution of my software and close it from code when I've finished.

**Comment by mariotoffia** [comment]
Interesting idea! I'll investigate hopefully next weekend. Maybe extend the ```ConsoleStream<T>``` that I use in ```Logs``` command. This is currently used in read-only mode to e.g.
```cs
        using (var logs = _docker.Logs(id)) // No running in follow mode (thus it will exit itself)
        {
          while (!logs.IsFinished)
          {
            var line = logs.TryRead(5000);
            if (null == line)
            {
              Assert.AreEqual(true, logs.IsFinished, "Since null line, the process shall been shutdown");
              break;
            }

            Debug.WriteLine(line);
          }

          Assert.AreEqual(true, logs.IsFinished);
          Assert.AreEqual(true, logs.IsSuccess);
        }
```
where you can cancel an ongoing interactive session using
```cs
var token = new CancellationTokenSource();
// and use it like this
using (var logs = _docker.Logs(id,token.Token,true/*follow*/))
{
  // do
  var line = logs.TryRead(5000);
  // … while(…)
  token.Cancel(); // This will cancel the current session (logs.IsFinished == true)
}
```
The above run in follow mode and needs to be explicitly cancelled.

So e.g. a 
```cs
bool TryCommand(string command, param string []args)
``` 
on the ```ConsoleStream``` that sends it to ```StdIn``` and the outcome can be picked up using ```TryRead```.

This one needs a bit more thought. I'll come back this weekend.

Cheers,
 Mario

**Comment by lorenzo93** [comment]
From your comment I understand you are thinking about launching commands directly from code or putting something between the container console and the host console.

I was thinking about something user interactive, like the shell you open from powershell, where you can have direct access to the container console (otherwise you cannot do commands like "arrow up" to scroll history or "tab" for autocomplete of commands).

Something like you run my console app and from software I start some docker containers and open an interactive shell (opening new window) for each container.

**Comment by mariotoffia** [comment]
That's true - need to think on this - how to sove this properly

**Comment by lorenzo93** [comment]
I'm thinking about doing code platform specific and choosing if launch powershell (like below) or /bin/bash with something like this.
Giving the command `docker run -ti alpine /bin/sh` it should be able to do the trick.

Problems are two:
- does this work even through DockerMachine on remote hosts?
- the code under does not work, it should execute `docker ps` but instead prints docker ps on shell

`			var process = new Process()
			{
				StartInfo = new ProcessStartInfo
				{
					FileName = "C:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe",
					Arguments = "-NoLogo -NoExit -Command {docker ps}",
					RedirectStandardOutput = false,
					UseShellExecute = true,
					CreateNoWindow = false,
				}
			};
			process.Start();`

**Comment by mariotoffia** [comment]
I already do this on Linux when there's a need to do ```sudo``` with or without password where I fire up a bash instead of the docker binary. In that case it is just ```bash -c```. 

However I haven't tried feed commands to PowerShell and that is not what I think is the main problem. If we need to do something useful from the program and allow the user to interact we need to clone the stdin, stdout, and stderr to allow programmatic access while terminal access. The redirect, that's easy - to clone - that is what I need to investigate. 

Also PowerShell may be hosted etc. I think there are many things to consider, including what support .NET core do have and also how to handle mac. 

To do remote you have to use ssh for linux, mac based (much like how docker-machine with ssh is doing it). From there one can get the remote IP, CA certificate and key to use when doing ssh. I do remember that you can do remote PowerShell, but haven't tried it...

Therefore, for me there are many things to consider before bringing this into the library - but I'll have a shot :)

When it comes to powershell and execute, just remove the scopes around ```docker ps``` like this:
```cs
var process = new Process()
            {
                StartInfo = new ProcessStartInfo
                {
                    FileName = @"C:\windows\system32\windowspowershell\v1.0\powershell.exe", 
                    Arguments = "-NoLogo -NoExit -Command docker ps", 
                    RedirectStandardOutput = false, 
                    UseShellExecute = true, 
                    CreateNoWindow = false,
                }
            };
            process.Start();
```
and it will work.

I use triple backticks and cs + enter + code + enter + triple backtics for segment of code.

**Comment by lorenzo93** [comment]
Thank you, I modified my previous comment and now it is well formatted.
Thank you even for the correction of my snippet, I was following `powershell -help` instructions too literally ;)

**Comment by mariotoffia** [comment]
I've been doing a bit of investigation of this one... I could not find any way of both having the user do I/O and the program itself. In order to show the cmd, powershell or other console it needs to have ```ShellExecute = true``` and there's no way of getting standard I/O from that. It needs to use ```CreateProcess``` to have the ability to redirect I/O.

Having said that, it would be possible if the application using FluentDocker is a console, powershell or bash application. Then it can use that terminal to handle I/O and allow the program to do I/O as well...

I'm not done yet, but start to feel like this is not possible or more or less out of scope of this library. If anyone have any input it is much appreciated. 

Cheers,
 Mario
