### ISSUE TITLE
Naming Duplicate functions in different objects

### ISSUE THREAD

**Issue by lorenzo93** [mariotoffia/FluentDocker#67]
Hi,

today I'm working on creating docker networks.
Following the readme you use the function `_docker.NetworkCreate("name_of_network")` where _docker is an `DockerUri` object.

But on the `DockerHostService` you have the function `CreateNetwork` with the same behaviour.

Why they have different names?
Do you use a different naming for a reason or they are just the same function?

**Comment by mariotoffia** [comment]
Yes, since all commands (the ```NetworkCreate``` is a extension method on the ```DockerUri``` type) have the naming convention <TypeOfService><Command>(...) and the service do have the natural naming convention. The ```CreateNetwork``` do call  ```NetworkCreate``` underneath and create a NetworkService if successful. You don't need to care about ```Certificates``` and the ```Uri``` since that is already bound to current docker host.

Cheers,
 Mario

**Comment by lorenzo93** [comment]
Thanks, I thought they were created in different times and so had different naming
